FIX: Added missing NETWORKFPC check
I had a compilation error, and after some investigation found  accessing m_networkFPCControllerObject wasn't  wrapped in #ifdef NETWORKFPC here.

Here is the error I had:
error: member reference base type 'bool' is not a structure or union

 2050 |  m_cumulativeLookRotationDelta += m_networkFPCControllerObject->GetLookRotationDelta();